volumes:
  data:

services:
  postgres:
    container_name: postgres
    build:
      context: ./
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - env/.env_postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql

  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:latest
    env_file:
      - env/.env_keycloak
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy

  ms-crud-products:
    container_name: ms-crud-products
    build: ../ms-crud-products/.
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9091:9091"

  ms-gatway:
    container_name: ms-gatway
    build: ../ms-gatway/.
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"